Bugfix: Skip endtime to sort stations
The problem comes probably due to stations with same NSLC code and starttime. That shouldn't happen, but it is still somehow working with this code.

WARNING:root:Skipping download of inventory from endpoints
Traceback (most recent call last):
  File "./update-metadata.py", line 846, in <module>
    main()
  File "./update-metadata.py", line 652, in main
    ptStats.sort()
TypeError: can't compare datetime.datetime to NoneType